---

   - name: Actualizar paquetes.

     dnf:

       name: '*'

         state: lastest


   - name: Instalar repositorios epel-release.

      dnf:

        name:

          - epel-release

        state: present


   - name: Instalar phpmyadmin.

     dnf:

        name:

          - phpmyadmin

        state: present


   - name: importar archivo de configurción.

     copy:

       #src: recursos/phpmyadmin.conf

            dest: /etc/apache2/conf-available/phpmyadmin.conf

            content: |

          Alias /phpmyadmin /usr/share/phpMyAdmin

          <Directory /usr/share/phpMyAdmin/>
              AddDefaultCharset UTF-8

              <IfModule mod_authz_core.c>
                  <RequireAny>
                      Require ip 127.0.0.1
                      Require ip ::1
                      Require ip 192.168.10.0/24
                  </RequireAny>
              </IfModule>
              <IfModule !mod_authz_core.c>
                  Order Deny,Allow
                  Deny from All
                  Allow from 127.0.0.1
                  Allow from ::1
                  Allow from 192.168.10.
              </IfModule>
          </Directory>

            owner: root

            group: root

            mode: '0755'


    - name: Recargar httpd.

      service:

           name: httpd

           state: restarted
